module.exports = [
  {
    id: "TMFld0860EctVn2",
    title: "brand identity",
    is_public: true,
    user_id: 1,
    created_at: "2023-06-01",
    thumbnail: "board-img-1.png",
  },
  {
    id: "dcU4VO1Ik0Oa6cX",
    title: "blowgun mv",
    is_public: true,
    user_id: 1,
    created_at: "2023-03-26",
    thumbnail: "board-img-2.png",
  },
  {
    id: "edMDU5I-YtRe0Pu",
    title: "fashion",
    is_public: false,
    user_id: 1,
    created_at: "2023-10-09",
    thumbnail: "board-img-3.png",
  },
  {
    id: "L_XEx-ZHeZkPSVb",
    title: "uni work",
    is_public: true,
    user_id: 2,
    created_at: "2023-11-19",
    thumbnail: "explore1.png",
  },
  {
    id: 5,
    title: "studio board",
    is_public: true,
    user_id: 2,
  },
];
